//
//  Storage.swift
//  RealTimeCalculator
//
//  Created by Suheon Song on 2023/03/21.
//

import Foundation

struct Storage {
    let requestUrl = "https://quotation-api-cdn.dunamu.com/v1/forex/recent?codes=FRX.KRWUSD,FRX.KRWEUR,FRX.KRWJPY,FRX.KRWCNY,FRX.KRWHKD,FRX.KRWTWD,FRX.KRWGBP,FRX.KRWOMR,FRX.KRWCAD,FRX.KRWCHF,FRX.KRWSEK,FRX.KRWAUD,FRX.KRWNZD,FRX.KRWCZK,FRX.KRWCLP,FRX.KRWTRY,FRX.KRWMNT,FRX.KRWILS,FRX.KRWDKK,FRX.KRWNOK,FRX.KRWSAR,FRX.KRWKWD,FRX.KRWBHD,FRX.KRWAED,FRX.KRWJOD,FRX.KRWEGP,FRX.KRWTHB,FRX.KRWSGD,FRX.KRWMYR,FRX.KRWIDR,FRX.KRWQAR,FRX.KRWKZT,FRX.KRWBND,FRX.KRWINR,FRX.KRWPKR,FRX.KRWBDT,FRX.KRWPHP,FRX.KRWMXN,FRX.KRWBRL,FRX.KRWVND,FRX.KRWZAR,FRX.KRWRUB,FRX.KRWHUF,FRX.KRWPLN,FRX.KRWLKR,FRX.KRWDZD,FRX.KRWKES,FRX.KRWCOP,FRX.KRWTZS,FRX.KRWNPR,FRX.KRWRON,FRX.KRWLYD,FRX.KRWMOP,FRX.KRWMMK,FRX.KRWETB,FRX.KRWUZS,FRX
}
